In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
cwd= os.getcwd() # current working directory
path = os.path.join(cwd)

In [2]:
def get_train_set():
    print ('loading provided train set.')
    fp = os.path.join(path,'train.csv')
    df_train = pd.read_csv(fp, encoding='ISO-8859-1',low_memory=False) 
    return df_train


df_train= get_train_set ()
df_train.head()

loading provided train set.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
def get_test_set():    
    print ('loading provided test set .')
    fp = os.path.join(path,'test.csv')
    df_test = pd.read_csv(fp)  # , encoding = 'ISO-8859-1')

    return df_test

df_test= get_test_set()
df_test.head()
# df_test.describe()}
#list(df_test)

loading provided test set .

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
women=df_train.loc[df_train.Sex=="female"]['Survived']
rate_women=sum(women)/len(women)

print("% of women who survived:", rate_women)

% of women who survived: 0.7420382165605095

In [7]:
men=df_train.loc[df_train.Sex=="male"]['Survived']
rate_men=sum(men)/len(men)

print("% of men who survived:", rate_men)

% of men who survived: 0.18890814558058924

In [14]:
from sklearn.ensemble import RandomForestClassifier
y = df_train['Survived']

features = ['Pclass', "Sex", "SibSp", 'Parch']
X=pd.get_dummies(df_train[features])
X_test =pd.get_dummies(df_test[features])

model=RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X,y)

predications = model.predict(X_test)

output = pd.DataFrame({"passengerId":df_test.PassengerId, "Survived":predications})
output.to_csv("submission.csv",index=False)